#!/bin/sh

echo "opening tabs"

open https://github.com/ObjectIsAdvantag/DEVWKS-2043/blob/main/README.md

open https://editor.swagger.io/

echo "sleeping for 2 seconds to let the tabs open" 
sleep 2

clear

echo "please join the workshop folder with:"
echo "cd /home/devnet/DEVWKS-2043"


